import{pageShell,breadcrumb,sister,actions}from'../lib/layout.mjs';
const field=(label,name,type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" ${extra}></label>`;
export async function render({cfg,meta,path,css,scriptPath}){
 const crumbs=[{name:'Home',path:'/'},{name:'Contact',path}];
 const methods=[];if(cfg.contact.phone)methods.push(`<article class="card"><h2>Call</h2><p><a href="tel:${cfg.contact.phone}" data-track="call_click">${cfg.contact.phoneDisplay||cfg.contact.phone}</a></p></article>`);if(cfg.contact.whatsapp)methods.push(`<article class="card"><h2>WhatsApp a photo</h2><p><a href="https://wa.me/${cfg.contact.whatsapp}" data-whatsapp data-track="whatsapp_click">Start a WhatsApp message</a></p></article>`);if(cfg.contact.email)methods.push(`<article class="card"><h2>Email</h2><p><a href="mailto:${cfg.contact.email}">${cfg.contact.email}</a></p></article>`);if(!methods.length)methods.push(`<div class="placeholder-card">[PLACEHOLDER: phone, WhatsApp and email]</div>`);
 const availability=[cfg.contact.hours,cfg.contact.availabilityNote].filter(Boolean).join(' · ')||'[PLACEHOLDER: working hours and same-day note]';
 const form=cfg.forms.endpoint?`<form action="${cfg.forms.endpoint}" method="post" enctype="multipart/form-data" data-track-form><div class="form-grid">${field('Name','name','text','required autocomplete="name"')}${field('Phone','phone','tel','required autocomplete="tel"')}${field('Postcode','postcode','text','required autocomplete="postal-code"')}<label>What's the problem?<textarea name="problem" rows="6" required></textarea></label><label>Photo (optional, image files up to 10 MB)<input name="photo" type="file" accept="image/*"></label><label class="hp" aria-hidden="true">Leave this empty<input name="website" type="text" tabindex="-1" autocomplete="off"></label><p>We'll only use your details to reply to you. <a href="/privacy/">Privacy</a>.</p><button class="button button--primary" type="submit">Send message</button></div></form>`:`<p><strong>Online form coming soon — please call or WhatsApp.</strong></p>`;
 const main=`<div class="shell">${breadcrumb(crumbs)}</div><section class="hero"><div class="shell"><p class="eyebrow">Call · message · send a photo</p><h1>${meta.h1}</h1><p class="lede">Tell us the postcode, what is happening and what you can see. A photo often helps us identify the likely part before the visit.</p><div class="cards">${methods.join('')}</div><p class="availability">${availability}</p></div></section><section class="section section--alt"><div class="shell"><h2>What to send us</h2><ul><li>Your postcode</li><li>What the problem is doing now</li><li>A clear photo of the fitting and surrounding pipework if possible</li><li>The best time to reach you</li></ul>${form}</div></section><section class="section"><div class="shell"><h2>Our base</h2><p>Fulham Plumbing<br>36 Hurlingham Road<br>London SW6 3RQ</p><p>This is a working base, not a walk-in shop. All jobs are carried out at the customer's property.</p><h2>Areas covered</h2><p>Fulham SW6, Chelsea Harbour &amp; Lots Road SW10, Putney SW15 and Wandsworth Town SW18.</p><p><a href="/areas-we-cover/">See the full service area →</a> · <a href="/pricing/">Check pricing →</a></p>${sister(cfg)}</div></section><section class="section cta-band"><div class="shell"><h2>Ready to show us the problem?</h2>${actions(cfg)}</div></section>`;
 return pageShell({cfg,meta,path,css,scriptPath,main,breadcrumbs:crumbs});
}