import{pageShell,breadcrumb,actions}from'../lib/layout.mjs';
import{pricing}from'../lib/pricing.mjs';
export async function render({cfg,meta,path,css,scriptPath}){
 const p=pricing(cfg),crumbs=[{name:'Home',path:'/'},{name:'Landlords and agents',path}];
 const faqs=[{q:'Can you deal with tenants directly?',a:'Yes. With the landlord or agent’s authority, access can be arranged directly with the tenant so the person at the property gets the appointment details first hand.'},{q:'Do you invoice the agent?',a:'The invoice can be addressed to the agreed party. Any account terms are confirmed before work starts rather than assumed on the website.'},{q:'Can you send photos before and after?',a:'Yes. Where useful, photos can show the visible fault, the part that failed and the finished plumbing repair.'},{q:'Can you do a list of repairs between tenancies?',a:'Yes. Send the list with photos and we can group the plumbing items into one planned visit where practical.'}];
 const steps=[['Tenant access','With authority in place, the appointment can be arranged with the occupier.'],['Photos before and after','Photos can document the visible fault and the finished repair.'],['Clear invoicing',p.priceLine()+' Parts are shown separately at cost.'],['Between-tenancy lists','Running toilets, dripping taps, isolation valves and appliance connections can be grouped into one planned visit.']];
 const main=`<div class="shell">${breadcrumb(crumbs)}</div><section class="hero"><div class="shell"><p class="eyebrow">Landlords · letting agents · block managers</p><h1>${meta.h1}</h1><p class="lede">Repairs without the chasing: tenant access, photos, repair lists and clear invoices for managed properties.</p><div class="hero-actions">${actions(cfg)}</div></div></section>
 <section class="section"><div class="shell"><p class="eyebrow">How we work with agents</p><h2>Four things kept simple.</h2><div class="hairline-list">${steps.map(([h,t])=>`<div class="hairline-row"><span><strong>${h}</strong><small>${t}</small></span></div>`).join('')}</div></div></section>
 <section class="section section--alt"><div class="shell two-col"><div><p class="eyebrow">Typical work</p><h2>Repairs and checks.</h2><div class="hairline-list"><a class="hairline-row" href="/leak-repairs/"><span><strong>Leak repairs</strong><small>Trace and repair accessible plumbing leaks.</small></span><span class="arrow">→</span></a><a class="hairline-row" href="/toilet-repairs/"><span><strong>Toilet repairs</strong><small>Running cisterns, flush faults and leaks.</small></span><span class="arrow">→</span></a><a class="hairline-row" href="/plumbing-inspections/"><span><strong>Plumbing inspections</strong><small>Visible pipework, pressure, tanks, cylinders and written findings.</small></span><span class="arrow">→</span></a><a class="hairline-row" href="/small-plumbing-jobs/"><span><strong>Small plumbing jobs</strong><small>Group a list into one visit where practical.</small></span><span class="arrow">→</span></a></div></div><div><p class="eyebrow">Useful guide</p><h2>Water between flats.</h2><p>For water entering from another flat, read what to do first and how the source is traced.</p><p><a href="/guides/water-through-ceiling/">Water coming through the ceiling →</a></p></div></div></section>
 <section class="section"><div class="shell narrow"><p class="eyebrow">Questions</p><h2>Common questions.</h2><div class="faq-list">${faqs.map(f=>`<details><summary><h3>${f.q}</h3></summary><p>${f.a}</p></details>`).join('')}</div></div></section>
 <section class="cta-band"><div class="shell"><p class="eyebrow">Have a repair list?</p><h2>Send the postcode, access contact and photos.</h2><div class="hero-actions">${actions(cfg)}</div></div></section>`;
 return pageShell({cfg,meta,path,css,scriptPath,main,faqs,breadcrumbs:crumbs,service:{name:'Plumbing for landlords and agents',slug:null},bodyClass:'landlords-page'});
}