import{pageShell,breadcrumb,actions,exclusions}from'../lib/layout.mjs';
import{pricing}from'../lib/pricing.mjs';

export async function render({cfg,meta,path,css,scriptPath}){
 const p=pricing(cfg),crumbs=[{name:'Home',path:'/'},{name:'Pricing',path}];
 const jobs=[['Toilet fill valve','toilet-repairs'],['Basin mixer fitted','tap-repairs'],['Shower pump replaced','shower-pumps'],['Low-pressure diagnosis','low-water-pressure'],['Three small jobs in one visit','small-plumbing-jobs'],['Loft tank replaced','cold-water-tanks']];
 const rows=jobs.map(([n,s])=>{const x=cfg.services.find(a=>a.slug===s);return`<tr><th><a href="/${s}/">${n}</a></th><td>${p.typicalTimeText(x.typicalMinutes)}</td><td>${cfg.pricing.increment!=null?p.labourRange(x.typicalMinutes):'See note above'}</td><td>Parts at cost where used</td></tr>`}).join('');
 const faqs=[{q:"What's included in the first hour?",a:'Labour from arrival for up to the first hour. Parts are separate at cost and shown on the invoice.'},{q:'Is there a call-out fee?',a:'No. There is no separate call-out fee; the first-hour labour charge is the starting charge for a visit.'},{q:'How do you charge for parts?',a:'Parts are charged at cost and shown separately on the invoice.'},{q:'Do you give fixed quotes?',a:'For bigger jobs we can, after seeing it.'}];
 const main=`<div class="shell">${breadcrumb(crumbs)}</div>
 <section class="hero"><div class="shell"><p class="eyebrow">Straightforward pricing</p><h1>${meta.h1}</h1><p class="lede">Know how the visit is charged before anyone turns up.</p></div></section>
 <section class="section"><div class="shell"><div class="price-card"><div class="price-big">£${cfg.pricing.firstHour}</div><p><strong>first hour</strong></p><p>${p.incrementText()}.</p><p>No separate call-out fee. Parts at cost.</p></div></div></section>
 <section class="section section--alt"><div class="shell"><p class="eyebrow">How time is counted</p><h2>From arrival onwards.</h2><div class="steps"><div class="step"><div><h3>Arrive</h3><p>Chargeable time starts when we arrive at the property.</p></div></div><div class="step"><div><h3>First hour · £${cfg.pricing.firstHour}</h3><p>The first-hour labour charge covers up to the first hour.</p></div></div><div class="step"><div><h3>Then ${cfg.pricing.incrementMinutes}-minute steps</h3><p>${cfg.pricing.increment!=null?`Each further step is £${cfg.pricing.increment}.`:'The monetary amount for each 30-minute step will be published once confirmed.'}</p></div></div></div></div></section>
 <section class="section"><div class="shell"><p class="eyebrow">Worked examples</p><h2>Typical jobs.</h2>${cfg.pricing.increment==null?`<p><strong>Labour starts at £${cfg.pricing.firstHour} for the first hour.</strong> Because the later increment is not yet published, examples below show the likely time rather than an invented total.</p>`:''}<div class="table-wrap"><table><thead><tr><th>Job</th><th>Typical time</th><th>Labour</th><th>Parts</th></tr></thead><tbody>${rows}</tbody></table></div><p><a href="/small-plumbing-jobs/">Group small jobs into one visit →</a></p></div></section>
 <section class="section section--alt"><div class="shell two-col"><div><p class="eyebrow">Included</p><h2>What the labour covers.</h2><p>Diagnosis and plumbing labour within the booked visit, with parts shown separately at cost.</p></div><div><p class="eyebrow">Separate unless agreed</p><h2>What isn't included.</h2><p>Making good, decorating and electrical work are separate unless specifically quoted. We explain where another trade is needed.</p></div></div>${cfg.pricing.inspectionFixedPrice!=null?`<div class="shell" style="margin-top:24px"><p><strong>Plumbing inspection: ${p.inspectionPriceText()}</strong> · <a href="/plumbing-inspections/">See what the inspection covers →</a></p></div>`:''}</section>
 <section class="section"><div class="shell narrow"><p class="eyebrow">Questions</p><h2>Pricing questions.</h2><div class="faq-list">${faqs.map(f=>`<details><summary><h3>${f.q}</h3></summary><p>${f.a}</p></details>`).join('')}</div>${exclusions(cfg)}</div></section>
 <section class="cta-band"><div class="shell"><p class="eyebrow">Need a realistic idea first?</p><h2>Tell us what needs doing.</h2><p>A photo and short list help us judge the likely time before the visit.</p><div class="hero-actions">${actions(cfg)}</div></div></section>`;
 const offer={'@type':'Offer',name:'First hour of labour',price:String(cfg.pricing.firstHour),priceCurrency:'GBP',eligibleRegion:{'@type':'Place',name:'Fulham, London'}};
 return pageShell({cfg,meta,path,css,scriptPath,main,faqs,breadcrumbs:crumbs,offer,bodyClass:'pricing-page'});
}